version: '3.2'
services:
  postgres-avenger:
    image: postgres
    environment:
      POSTGRES_USER: tortora.avenger
      POSTGRES_DB: avengers
      POSTGRES_PASSWORD: tortora.avenger
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "25433:5432"
    volumes:
      - pdb12:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-avenger:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: avengers@email.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5556:80"
    depends_on:
      - postgres-avenger
    networks:
      - postgres-compose-network

volumes:
  pdb12:
networks:
  postgres-compose-network:
    driver: bridge